// AUTH
export const FETCH_TOKEN_START = "FETCH_TOKEN_START";
export const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS";
export const FETCH_TOKEN_FAIL = "FETCH_TOKEN_FAIL";

// PLAYLIST
export const FETCH_PLAYLIST_START = "FETCH_PLAYLIST_START";
export const FETCH_PLAYLIST_SUCCESS = "FETCH_PLAYLIST_SUCCESS";
export const FETCH_PLAYLIST_FAIL = "FETCH_PLAYLIST_FAIL";

// PLAYER
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const SET_RANDOM_TRACK = "SET_RANDOM_TRACK";
export const NEXT_TRACK = "NEXT_TRACK";
export const PREV_TRACK = "PREV_TRACK";
